{
  "chaoslib-version": "1.29.0",
  "platform": "Linux-5.15.0-1022-azure-x86_64-with-glibc2.31",
  "node": "fv-az225-949",
  "experiment": {
    "tags": [
      "aws",
      "az",
      "kubernetes"
    ],
    "title": "Losing an AZ should not impact availability",
    "method": [
      {
        "name": "Inject mild load into our application",
        "type": "action",
        "provider": {
          "path": "ddosify",
          "type": "process",
          "arguments": "-d 330 -n 150 -o stdout-json -t http://k8s-default-lbdemo-b42659e47c-1929532341.eu-central-1.elb.amazonaws.com/consumer/data"
        },
        "background": true
      },
      {
        "name": "Simulate AZ Failure for ALB",
        "type": "action",
        "pauses": {
          "after": 300
        },
        "provider": {
          "func": "fail_az",
          "type": "python",
          "module": "azchaosaws.elbv2.actions",
          "arguments": {
            "az": "eu-central-1b",
            "tags": [
              {
                "Key": "ingress.k8s.aws/stack",
                "Value": "default/lb-demo"
              }
            ],
            "dry_run": false
          }
        }
      }
    ],
    "secrets": {
      "slack": {
        "token": {
          "key": "SLACK_TOKEN",
          "type": "env"
        }
      }
    },
    "controls": [
      {
        "name": "reliably",
        "provider": {
          "type": "python",
          "module": "chaosreliably.controls.experiment",
          "arguments": {
            "exp_id": "4e6f6a1f-ebac-41c0-be7b-ac79803d896a",
            "org_id": "8f67bb6a-4944-40af-80b0-921023467cdc"
          }
        }
      },
      {
        "name": "slack",
        "provider": {
          "type": "python",
          "module": "chaosslack.control",
          "secrets": [
            "slack"
          ],
          "arguments": {
            "channel": "chaosdemo"
          }
        }
      },
      {
        "name": "opentracing",
        "provider": {
          "type": "python",
          "module": "chaostracing.control"
        }
      },
      {
        "name": "reliably",
        "provider": {
          "type": "python",
          "module": "chaosreliably.controls.experiment",
          "arguments": {
            "exp_id": "5653c16d-1e17-44b4-9f12-2fea9b246749",
            "org_id": "8f67bb6a-4944-40af-80b0-921023467cdc"
          }
        }
      }
    ],
    "rollbacks": [
      {
        "name": "Recover AZ Failure for ALB",
        "type": "action",
        "provider": {
          "func": "recover_az",
          "type": "python",
          "module": "azchaosaws.elbv2.actions"
        }
      }
    ],
    "description": "Remove all subnets of a zone from the load balancer so that zone cannot be accessed anymore from the internet",
    "configuration": {
      "aws_region": "eu-central-1",
      "tracing_provider": "opentelemetry",
      "tracing_opentelemetry_exporter": "oltp-http",
      "tracing_opentelemetry_baggage_prefix": "b3",
      "tracing_opentelemetry_collector_endpoint": "https://api.honeycomb.io/v1/traces"
    },
    "contributions": {
      "latency": "low",
      "security": "none",
      "availability": "high"
    },
    "steady-state-hypothesis": {
      "title": "Users should always see the service available",
      "probes": [
        {
          "name": "get-lb-unavailable-service-error-count-during-the-last-5m",
          "type": "action",
          "provider": {
            "func": "get_metric_statistics",
            "type": "python",
            "module": "chaosaws.cloudwatch.probes",
            "arguments": {
              "duration": 300,
              "namespace": "AWS/ApplicationELB",
              "statistic": "Sum",
              "metric_name": "HTTPCode_ELB_503_Count",
              "dimension_name": "LoadBalancer",
              "dimension_value": "app/k8s-default-lbdemo-b42659e47c/bcdbe82dbd3b2dea"
            }
          },
          "tolerance": 0
        }
      ]
    },
    "dry": null
  },
  "start": "2022-10-24T13:20:57.881960",
  "status": "completed",
  "deviated": false,
  "steady_states": {
    "before": {
      "steady_state_met": true,
      "probes": [
        {
          "activity": {
            "name": "get-lb-unavailable-service-error-count-during-the-last-5m",
            "type": "action",
            "provider": {
              "func": "get_metric_statistics",
              "type": "python",
              "module": "chaosaws.cloudwatch.probes",
              "arguments": {
                "duration": 300,
                "namespace": "AWS/ApplicationELB",
                "statistic": "Sum",
                "metric_name": "HTTPCode_ELB_503_Count",
                "dimension_name": "LoadBalancer",
                "dimension_value": "app/k8s-default-lbdemo-b42659e47c/bcdbe82dbd3b2dea"
              }
            },
            "tolerance": 0
          },
          "output": 0,
          "status": "succeeded",
          "start": "2022-10-24T13:20:58.417746",
          "end": "2022-10-24T13:20:58.855218",
          "duration": 0.437472,
          "tolerance_met": true
        }
      ]
    },
    "after": {
      "steady_state_met": true,
      "probes": [
        {
          "activity": {
            "name": "get-lb-unavailable-service-error-count-during-the-last-5m",
            "type": "action",
            "provider": {
              "func": "get_metric_statistics",
              "type": "python",
              "module": "chaosaws.cloudwatch.probes",
              "arguments": {
                "duration": 300,
                "namespace": "AWS/ApplicationELB",
                "statistic": "Sum",
                "metric_name": "HTTPCode_ELB_503_Count",
                "dimension_name": "LoadBalancer",
                "dimension_value": "app/k8s-default-lbdemo-b42659e47c/bcdbe82dbd3b2dea"
              }
            },
            "tolerance": 0
          },
          "output": 0,
          "status": "succeeded",
          "start": "2022-10-24T13:26:30.240763",
          "end": "2022-10-24T13:26:30.641558",
          "duration": 0.400795,
          "tolerance_met": true
        }
      ]
    },
    "during": []
  },
  "run": [
    {
      "activity": {
        "name": "Inject mild load into our application",
        "type": "action",
        "provider": {
          "path": "ddosify",
          "type": "process",
          "arguments": "-d 330 -n 150 -o stdout-json -t http://k8s-default-lbdemo-b42659e47c-1929532341.eu-central-1.elb.amazonaws.com/consumer/data"
        },
        "background": true
      },
      "output": {
        "status": 0,
        "stdout": "{\"success_perc\":0,\"fail_perc\":100,\"success_count\":0,\"fail_count\":150,\"avg_duration\":0,\"steps\":{\"1\":{\"name\":\"\",\"status_code_dist\":{},\"error_dist\":{\"dial tcp: lookup k8s-default-lbdemo-b42659e47c-1929532341.eu-central-1.elb.amazonaws.com on 127.0.0.53:53: no such host\":150},\"durations\":{},\"success_count\":0,\"fail_count\":150,\"success_perc\":0,\"fail_perc\":100}}}\n",
        "stderr": ""
      },
      "status": "succeeded",
      "start": "2022-10-24T13:20:59.550768",
      "end": "2022-10-24T13:26:29.659593",
      "duration": 330.108825
    },
    {
      "activity": {
        "name": "Simulate AZ Failure for ALB",
        "type": "action",
        "pauses": {
          "after": 300
        },
        "provider": {
          "func": "fail_az",
          "type": "python",
          "module": "azchaosaws.elbv2.actions",
          "arguments": {
            "az": "eu-central-1b",
            "tags": [
              {
                "Key": "ingress.k8s.aws/stack",
                "Value": "default/lb-demo"
              }
            ],
            "dry_run": false
          }
        }
      },
      "output": null,
      "status": "failed",
      "exception": [
        "Traceback (most recent call last):\n",
        "  File \"/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaoslib/provider/python.py\", line 56, in run_python_activity\n    return func(**arguments)\n",
        "  File \"/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/azchaosaws/utils.py\", line 16, in wrapper\n    return fn(**kwargs)\n",
        "  File \"/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/azchaosaws/elbv2/actions.py\", line 81, in fail_az\n    raise FailedActivity(\"[ELBV2] No LBs in the target AZ found...\")\n",
        "chaoslib.exceptions.ActivityFailed: [ELBV2] No LBs in the target AZ found...\n",
        "\nDuring handling of the above exception, another exception occurred:\n\n",
        "chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: [ELBV2] No LBs in the target AZ found...\n"
      ],
      "start": "2022-10-24T13:20:59.568287",
      "end": "2022-10-24T13:21:00.049198",
      "duration": 0.480911
    }
  ],
  "rollbacks": [
    {
      "activity": {
        "name": "Recover AZ Failure for ALB",
        "type": "action",
        "provider": {
          "func": "recover_az",
          "type": "python",
          "module": "azchaosaws.elbv2.actions"
        }
      },
      "output": null,
      "status": "failed",
      "exception": [
        "Traceback (most recent call last):\n",
        "  File \"/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaoslib/provider/python.py\", line 56, in run_python_activity\n    return func(**arguments)\n",
        "  File \"/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/azchaosaws/elbv2/actions.py\", line 173, in recover_az\n    state_path = validate_fail_az_path(\n",
        "  File \"/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/azchaosaws/helpers.py\", line 42, in validate_fail_az_path\n    raise FailedActivity(\n",
        "chaoslib.exceptions.ActivityFailed: [ELBV2] To rollback AZ failure, you must specify the path to the file generated from fail_az (fail_az.elbv2.json)\n",
        "\nDuring handling of the above exception, another exception occurred:\n\n",
        "chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: [ELBV2] To rollback AZ failure, you must specify the path to the file generated from fail_az (fail_az.elbv2.json)\n"
      ],
      "start": "2022-10-24T13:26:31.404674",
      "end": "2022-10-24T13:26:31.406111",
      "duration": 0.001437
    }
  ],
  "end": "2022-10-24T13:26:31.902302",
  "duration": 334.02231192588806
}